### PR TITLE
Kevin/fix default font feature settings error

### LINKED ISSUE #9: Plugin is broken if you select a text layer that doesn’t have any modifications
Since I kept testing with a text layer with some `NSFontFeatureSettingsAttribute` I didn’t notice the fact that if this is `null` then the whole plugin breaks… which is really bad considering most, if not all fonts, that you select in sketch return `null`

### PR DESCRIPTION
**Pull request by KevinGutowski**
Fixes #9

### CODE REVIEW

**Comment by KevinGutowski** [comment]
Fixes #3

File: src/my-command.js [hunk 1]
```diff
@@ -540,7 +540,17 @@ function updateFontFeatureSettingsAttribute(settingsAttribute) {
     const descriptor = font.fontDescriptor().fontDescriptorByAddingAttributes(settingsAttribute)
 
     const newFont = NSFont.fontWithDescriptor_size(descriptor,fontSize)
-    textLayer.sketchObject.setFont(newFont)
+
+    if (textLayer.sketchObject.isEditingText() == 1) {
+        // In Edit Mode
+        console.log("In Edit Mode")
+        let textStorage = textLayer.sketchObject.editingDelegate().textStorage()
+        textStorage.beginEditing()
```
Comment (KevinGutowski) [inline src/my-command.js]: Comment here

File: src/my-command.js [hunk 2]
```diff
@@ -589,8 +599,12 @@ function updateUI() {
     // Update uiSettings array
     // need to do this because fontFeatureSettings only has
     // settings for applied options (doesn't contain state for all options)
-    var updatedUISettings = modifyUISettings(fontFeatureSettings, defaultUISettings)
```
Comment (KevinGutowski) [inline src/my-command.js]: gkjhhgk

File: src/my-command.js [hunk 3]
```diff
@@ -589,8 +599,12 @@ function updateUI() {
...
-    // console.log(updatedUISettings)
+    var updatedUISettings
```
Comment (KevinGutowski) [inline src/my-command.js]: kjhgkjhgk
